pre_bump_hooks = [
	"git fetch --all --tags"
]

post_bump_hooks = [
	"git push",
	"git push --tags"
]

[commit_types]
feat = { changelog_title = "Features", bump_minor = true }
fix = { changelog_title = "Bug Fixes", bump_patch = true }
imp = { changelog_title = "Improvements", bump_patch = true }
ci = { changelog_title = "Build / CI", bump_patch = true }
chore = { changelog_title = "Chores", omit_from_changelog = true }
