endpoints:
  ABC123:
    printer:
      device: /dev/usb/lp4
      direction: normal
      label:
        width: 50
        height: 30
        gap: 2
        offset: 0
    args:
      ProductName: product_name
      Id: product.id
      Expiration: expiration
      Manufacturer: manufacturer
    code:
      - type: text
        x: 200
        y: 16
        font: "4"
        align: center
        content: "{{ .ProductName }}"
      - type: qr
        x: 20
        y: 56
        ecc: L
        cellWidth: 5
        content: "{{ .Id }}"
      - type: text
        x: 20
        y: 174
        font: "2"
        align: left
        content: "DD = {{ .Expiration }}"
      - type: text
        x: 200
        y: 202
        font: "1"
        align: "center"
        content: "MFR {{ .Manufacturer }}"
  grocy-label:
    printer:
      device: /dev/usb/lp4
      direction: inverted
      label:
        width: 50
        height: 30
        gap: 2
        offset: 0
    args:
      Product: product
      Code: grocycode
      Amount: stock_entry.amount
      Unit: details.quantity_unit_stock.name
      EntranceDate: stock_entry.purchased_date
      DueDate: stock_entry.best_before_date
    code:
      - type: qr
        x: 10
        y: 40
        ecc: L
        cellWidth: 5
        content: "{{ .Code }}"
      - type: text
        x: 150
        y: 16
        font: "3"
        content: "{{ if gt (len .Product) 14 }}{{ slice .Product 0 14 }}{{ else }}{{ .Product }}{{ end }}"
      - type: text
        x: 150
        y: 44
        font: "3"
        content: "{{ if gt (len .Product) 14 }}{{ slice .Product 14 }}{{ end }}"
      - type: text
        x: 150
        y: 90
        font: "4"
        content: "{{ .Amount }} {{ .Unit }}"
      - type: text
        x: 150
        y: 180
        font: "2"
        content: "Ent: {{ .EntranceDate }}"
      - type: text
        x: 150
        y: 204
        font: "2"
        content: "Exp: {{ .DueDate }}"
