endpoints:
  ABC123:
    printer:
      device: /dev/usb/lp4
      direction: normal
      label:
        width: 50
        height: 30
        gap: 2
        offset: 0
    args:
      ProductName: product_name
      Id: product.id
      Expiration: expiration
      Manufacturer: manufacturer
    code:
      - type: text
        x: 200
        y: 16
        font: "4"
        align: center
        content: "{{ .ProductName }}"
      - type: qr
        x: 20
        y: 56
        ecc: L
        cellWidth: 5
        content: "{{ .Id }}"
      - type: text
        x: 20
        y: 174
        font: "2"
        align: left
        content: "DD = {{ .Expiration }}"
      - type: text
        x: 200
        y: 202
        font: "1"
        align: "center"
        content: "MFR {{ .Manufacturer }}"
  grocy-label:
    printer:
      device: /dev/usb/lp4
      direction: inverted
      label:
        width: 50
        height: 30
        gap: 2
        offset: 0
    args:
      Product: product
      Code: grocycode
      DueDate: due_date
    code:
      - type: qr
        x: 16
        y: 16
        ecc: L
        cellWidth: 5
        content: "{{ .Code }}"
      - type: text
        x: 160
        y: 16
        font: "3"
        content: "{{ .Product }}"
      - type: text
        x: 160
        y: 204
        font: "2"
        content: "Exp.: {{ slice .DueDate 4 }}"
