endpoints:
  ABC123:
    printer:
      device: /dev/usb/lp0
      label:
        width: 50
        height: 30
        gap: 2
        offset: 0
    args:
      ProductName: product_name
      Id: id
      Expiration: expiration
      Manufacturer: manufacturer
    code:
      - type: text
        x: 20
        y: 16
        font: "4"
        align: center
        content: "{{ .ProductName }}"
      - type: barcode
        x: 20
        y: 56
        height: 80
        codeType: "128"
        humanReadable: center
        align: center
        content: "{{ .Id }}"
      - type: text
        x: 20
        y: 174
        font: "2"
        align: left
        content: "DD = {{ .Expiration }}"
      - type: text
        x: 20
        y: 202
        font: "1"
        align: "center"
        content: "MFR {{ .Manufacturer }}"
